### ISSUE TITLE
Error compiling with library installed from library manager

### ISSUE THREAD

**Issue by wero1414** [sparkfun/SparkFun_CCS811_Arduino_Library#14] opened 2019-01-16 16:02 UTC
I can see that the problem was fixed by this PR #10, so i think that the problem is that you havent done realese of this update in order to update the library on the arduino library manager

**Comment by sabas1080** [comment] 2019-01-18 16:22
+1

**Comment by nseidle** [comment] 2019-01-24 00:04
Sorry folks! I broke it. I just pushed v1.0.7 to try to fix this. 

There's something fishy going on with the Arduino library manager as well

![image](https://user-images.githubusercontent.com/117102/51645304-edcc6f00-1f30-11e9-914c-f3e38a208b69.png)

The library isn't showing up at all. I'll check it tomorrow and file an issue with Arduino if it doesn't resolve over night.

**Comment by bboyho** [comment] 2019-06-01 00:17
I was updating something else with the CCS811 when I came across this issue. Testing v1.0.7 out, I was able to compile, upload the code, and read the sensor.

It looks like the issue is fixed so I will be closing this issue out. If we need  we can always open this issue back up. ;)

**Closed by bboyho** 2019-06-01 00:17 UTC
