### ISSUE TITLE
ESP8266 error

### ISSUE THREAD

**Issue by hsadeghilam** [sparkfun/SparkFun_CCS811_Arduino_Library#11] opened 2018-09-26 20:54 UTC
I just updated my library and got an error:

C:\Users\XXXX\Documents\Arduino\libraries\SparkFun_CCS811_Breakout\src\SparkFunCCS811.cpp:61:8: error: macro names must be identifiers

 #ifdef (ARDUINO_ARCH_ESP32 ARDUINO_ARCH_ESP8266)

**Comment by per1234** [comment] 2018-09-27 03:46
Duplicate of https://github.com/sparkfun/SparkFun_CCS811_Arduino_Library/issues/9, which was already fixed by https://github.com/sparkfun/SparkFun_CCS811_Arduino_Library/pull/10.

There hasn't been a release since the fix so you would either need to download and install the beta version of the library from GitHub or just use Library Manager to roll back to the last good release.

**Comment by nseidle** [comment] 2018-10-12 16:13
Sorry. This will be fixed momentarily.

**Closed by nseidle** 2018-10-12 16:13 UTC
